version: "3.7"
services:
  calendar-postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - calendar
  calendar-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    depends_on:
      - database
    networks:
      - calendar
    ports:
      - "8080:8080"
  calendar-pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    env_file: .env
    depends_on:
      - calendar-postgres
    ports:
      - "5050:80"
    networks:
      - calendar
    restart: unless-stopped

volumes:
  api:
  database_postgres:

networks:
  calendar:
    driver: bridge
